[target.aarch64-unknown-linux-gnu]
pre-build = [
  "dpkg --add-architecture $CROSS_DEB_ARCH",
  "apt update && apt install -y libssl-dev:$CROSS_DEB_ARCH"
]

[target.x86_64-unknown-linux-gnu]
pre-build = [
  "dpkg --add-architecture $CROSS_DEB_ARCH",
  "apt update && apt install -y libssl-dev:$CROSS_DEB_ARCH"
]
