---
name: cache

on:
  push:
    branches:
      - develop
      - fix/[0-9]+.[0-9]+.[0-9]+

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Run npm install
        run: npm install

  cargo:
    strategy:
      matrix:
        target:
          - name: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - name: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - name: x86_64-apple-darwin
            os: macos-latest
    name: cargo (${{ matrix.target.name }})
    runs-on: ${{ matrix.target.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target.name }}

      - name: Restore cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target
          key: ${{ matrix.target.name }}-cargo-${{ hashFiles('Cargo.lock') }}

      - name: Run cross build (debug)
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.target.name }}

      - name: Run cross build (release)
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.target.name }} --release

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: projectctl-${{ matrix.target.name }}-${{ github.head_ref }}
          path: target/${{ matrix.target.name }}/release/projectctl
          if-no-files-found: error
          retention-days: 1

  pip:
    needs: [cargo]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Restore cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target
          key: x86_64-unknown-linux-gnu-cargo-${{ hashFiles('Cargo.lock') }}

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
