---
name: ci

on:
  pull_request:
    paths:
      - .github/workflows/ci.yml
      - examples/**
      - "resources/**"
      - "Cargo.*"
      - "**.rs"

concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}-${{ github.workflow }}

jobs:
  build:
    strategy:
      matrix:
        target:
          - name: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - name: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - name: x86_64-apple-darwin
            os: macos-latest
    name: build (${{ matrix.target.name }})
    runs-on: ${{ matrix.target.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target.name }}

      - name: Restore cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target
          key: ${{ matrix.target.name }}-cargo-${{ hashFiles('Cargo.lock') }}

      - name: Run cross build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.target.name }}

  pre-commit:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Restore cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target
          key: x86_64-unknown-linux-gnu-cargo-${{ hashFiles('Cargo.lock') }}

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  test:
    needs: [build]
    strategy:
      matrix:
        target:
          - name: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - name: x86_64-apple-darwin
            os: macos-latest
    name: test (${{ matrix.target.name }})
    runs-on: ${{ matrix.target.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target.name }}

      - name: Restore cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target
          key: ${{ matrix.target.name }}-cargo-${{ hashFiles('Cargo.lock') }}

      - name: Configure git user/email
        run: |
          git config --global user.name "$(git log -n 1 --pretty=format:%an)"
          git config --global user.email "$(git log -n 1 --pretty=format:%ae)"

      - name: Run cross test
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --target ${{ matrix.target.name }}

  scenario:
    needs: [build]
    strategy:
      matrix:
        target:
          - name: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - name: x86_64-apple-darwin
            os: macos-latest
    name: run test scenario (${{ matrix.target.name }})
    runs-on: ${{ matrix.target.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target.name }}

      - name: Restore cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target
          key: ${{ matrix.target.name }}-cargo-${{ hashFiles('Cargo.lock') }}

      - name: Run scenario
        shell: bash -ex {0}
        run: |
          function assert_var {
            if [[ $2 != $3 ]]; then
              2>&1 echo "$1: expected \`$3\`, got \`$2\`"
              exit 1
            fi
          }

          PATH=$(pwd)/target/${{ matrix.target.name }}/debug:$PATH
          PROJECT_DIR=~/test

          git config --global user.name "$(git log -n 1 --pretty=format:%an)"
          git config --global user.email "$(git log -n 1 --pretty=format:%ae)"
          projectctl -vvv new rs-lib test $PROJECT_DIR
          cp examples/projectctl.yml $PROJECT_DIR/projectctl.local.yml
          cd $PROJECT_DIR
          eval $(projectctl -vvv env)
          assert_var DEBUG $DEBUG true
          assert_var HOST $HOST localhost
          assert_var PORT $PORT 9090
          if ! grep "^$(pwd)\$" ~/.projectctl/allowed-dirs > /dev/null; then
            2>&1 echo "`$(pwd)` should be added in ~/.projectctl/allowed-dirs"
            exit 1
          fi
          cd ..
          projectctl -vvv destroy $PROJECT_DIR
          if [[ -d $PROJECT_DIR ]]; then
            2>&1 echo "$PROJECT_DIR should be deleted"
            exit 1
          fi
          if grep "^$(pwd)\$" ~/.projectctl/allowed-dirs > /dev/null; then
            2>&1 echo "`$(pwd)` should be removed from ~/.projectctl/allowed-dirs"
            exit 1
          fi
